# Generated by Django 3.1.2 on 2021-10-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='html',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='markdown',
            field=models.TextField(),
        ),
    ]
