# Generated by Django 3.1.2 on 2021-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_doc_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='doc_path',
            field=models.CharField(default='Documents/Leverage', max_length=200),
        ),
    ]
