# Generated by Django 4.0.4 on 2022-08-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_recipient_alter_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='messenger.person'),
        ),
    ]
