# Generated by Django 4.0.4 on 2022-06-13 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='swplan.developer'),
            preserve_default=False,
        ),
    ]
