# Generated by Django 4.0.4 on 2022-06-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swplan', '0002_developer_user_project_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('order', models.IntegerField()),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='swplan.project')),
            ],
        ),
    ]
