envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: whale-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: fierroe297/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: pythonwebapps-05-super-app
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: proj5
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: fierroe297/PythonWebApps
  name: pythonwebapps-04-super-app-sta
  routes:
  - path: /static
  source_dir: proj5/static
