# Generated by Django 3.1.2 on 2021-11-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20211102_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('chapter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='book.chapter')),
            ],
        ),
    ]
