# Generated by Django 3.1.2 on 2021-11-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='chapter',
        ),
    ]
