# Generated by Django 3.1.2 on 2021-11-06 16:04

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_image_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.CharField(default='book', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=book.models.get_upload),
        ),
    ]
