# Generated by Django 4.0.4 on 2022-06-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('milestone', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='plan.milestone')),
            ],
        ),
    ]
