# Generated by Django 3.1.2 on 2021-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='expected',
            field=models.TextField(default='Initial Output'),
        ),
        migrations.AlterField(
            model_name='test',
            name='source',
            field=models.TextField(verbose_name='none'),
        ),
    ]
