# Generated by Django 3.1.2 on 2021-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer', '0005_auto_20211128_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='source',
            field=models.TextField(default='none'),
        ),
    ]
