# Generated by Django 3.1.2 on 2021-10-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20211015_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.CharField(default='Leverage Principle', max_length=200),
        ),
    ]
