# Generated by Django 3.1.2 on 2021-10-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20211019_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='doc_path',
            field=models.CharField(default='Leverage Principle', max_length=200),
        ),
    ]
