# Generated by Django 4.0.4 on 2022-06-05 12:53

from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=photos.models.get_upload)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='photogram',
            name='image',
        ),
        migrations.AddField(
            model_name='photogram',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.image'),
        ),
    ]
