# Generated by Django 3.2.7 on 2021-11-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_book_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapter',
            new_name='Lesson',
        ),
    ]
