# Generated by Django 3.2.7 on 2021-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_chapter_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='XXX', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='num_lessons',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='course',
            name='num_projects',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No Description is Set'),
        ),
    ]
