# Generated by Django 3.1.2 on 2021-11-05 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='book.chapter')),
            ],
        ),
    ]
