# Generated by Django 4.1 on 2022-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='strengths',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='weaknesses',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
