# Generated by Django 3.1.2 on 2021-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
